name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: 'ubuntu-latest'
        steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Deploy to ec2
           uses: easingthemes/ssh-deploy@v1.0.3
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.PRIVATE_KEY }}
             script: |
               cd ~/devops-1
               git pull origin master
               npm install
               pm2 restart 0
